version: "3"
services:
  gateway:
    image: openmrs/openmrs-reference-application-3-gateway:${TAG:-qa}
    restart: "unless-stopped"
    environment:
      - DOMAIN    
    ports:
      - "80:80"
    volumes:
      - ./gateway/templates-initiate:/etc/nginx/templates
      - ./gateway/etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - gateway
    command: >- 
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email ${EMAIL} --agree-tos --no-eff-email
             -d ${DOMAIN}
    volumes:
      - ./openmrs/gateway/etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot